sudo: false
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

env:
  - DJANGO_VERSION=2.2

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install Django==$DJANGO_VERSION
  - pip install -e .
  - pip install nose django_nose ddt
  - pip install python-coveralls

script:
  - coverage run --source dedal runtests.py

after_success:
  - coveralls
