# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('www', models.URLField()),
                ('body', models.TextField()),
            ],
        ),
    ]
