# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(to='blog.Comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='www',
            field=models.URLField(help_text='Enter address to your website.', verbose_name='Website'),
        ),
    ]
